### ISSUE TITLE
Issues on Setup (Windows)

### ISSUE THREAD

**Issue by matthiscock** [garrett9/app-ignition-laradock#6]
### Description:
Two Issues

Minor
Known hosts mismatch when using GIT
https://i.imgur.com/4hZFdLQ.png
Easily resolved but worth documenting

Major
Getting a error with a command, which is preventing competition. 
https://i.imgur.com/LULTHXe.png

### Expected Behavior:
No error and completion of installation of app

### Context information:

**Output of `git rev-parse HEAD`**

```
{paste here}
```

**Output of `docker version`**

```
{paste here}
```

**Output of `docker-compose version`**

```
{paste here}
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
Windows 11, up to date
```

### Steps to reproduce the issue:

1. Follow install instructions
2. New App, with DB (Postgres) 
3. Laravel 10

### Stacktrace & Additional info:

```
{paste here}
```

**Comment by garrett9** [comment]
Thanks for your submission! I'll take a look at this later today.

**Comment by garrett9** [comment]
@matthiscock The Postgres issue has been resolved in version 1.6.1. Docker Desktop doesn't update versions right away when they're published, so it could take a couple of hours.

I'll be reviewing some good ways to resolve the SSH issue and will update the thread once done.

**Comment by matthiscock** [comment]
I can confirm this is sorted - and now proceeds throught.

The known hosts is still there (but on your radar)

**Comment by garrett9** [comment]
@matthiscock In the screenshot you provided, that was due to a permissions issue. I pushed a fixed in the next release that will automatically adjust the permissions of the SSH file to be more secure, so that should no longer be an issue.

I see a few others have experienced the known hosts issue as well, though. I'm adding a troubleshooting section to the documentation, though.

**Comment by garrett9** [comment]
Documentation has been added for Unix systems, and an installation setup screen has been added to the Docker extension to aid with it: https://app-ignition.com/docs/1.0/installation#git
